[package]
name = "shawl"
version = "1.1.1"
authors = ["mtkennerly <mtkennerly@gmail.com>"]
edition = "2018"
description = "Windows service wrapper for arbitrary commands"
repository = "https://github.com/mtkennerly/shawl"
readme = "README.md"
license = "MIT"
default-run = "shawl"

[dependencies]
clap = { version = "3.2.23", features = ["derive"] }
ctrlc = "3.2.3"
flexi_logger = "0.15"
log = "0.4"
winapi = { version = "0.3.9", features = ["wincon"] }
windows-service = "0.5.0"

[dev-dependencies]
regex = "1.6.0"
speculate = "0.1.2"

[build-dependencies]
winres = "0.1.12"
static_vcruntime = "2.0"

[profile.release]
strip = true
lto = true
opt-level = "s"
panic = "abort"